name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print env and Set image TAG with lower-cased repository name
        run: |
          echo "Repository: ${REPOSITORY,,}"
          echo "Commit SHA: ${GITHUB_SHA}"
          echo "TAG=ghcr.io/${REPOSITORY,,}:${GITHUB_SHA},ghcr.io/${REPOSITORY,,}:${GITHUB_REFNAME}" >>${GITHUB_ENV}
          
        env:
          REPOSITORY: '${{ github.repository }}'
          GITHUB_SHA: '${{ github.sha }}'
          GITHUB_REFNAME: '${{ github.ref_name }}'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.TAG }} 
          file: Dockerfile
