name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image TAG with lower-cased repository name
        run: |
          echo "TAG=ghcr.io/${REPOSITORY,,}:${GITHUB_SHA}" >>${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'
          GITHUB_SHA: '${{ env.GITHUB_SHA }}'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.GITHUB_SHA }} 
          file: Dockerfile
